### ISSUE TITLE
Bug in the code of anomaly detection.

### ISSUE THREAD

**Issue by caixd-220529** [duanjufang/MF-CLR#1]
您好，非常感谢您的工作。在EXP_AD_PUBLIC_DATASETS.p的这一行中：https://github.com/duanjufang/MF-CLR/blob/4240bccb9fc7ea241a1936072118bed8aa6cb540/EXP_AD_PUBLIC_DATASETS.py#L537
我注意到用于测试的时间序列及其对应的特征被shuffle了，可是在之后的代码中，您似乎认为用于测试的序列和特征没有被shuffle，并且使用没有经过shuffle的标签来验证模型的性能？
请问您为什么要进行shuffle操作呢？

**Comment by duanjufang** [comment]
train和test都进行了shuffle，train之后又分出了真正的90%的train和10%的valid。这里的shuffle是在instance维上进行的，是对不同的样本间进行的打乱。希望可以回答到你的问题

**Comment by caixd-220529** [comment]
看到您的回复真的非常开心！想再问一下，如果我想复现DLinear等模型的异常检测结果，如果直接将您的工作中构造的数据集替换掉[Time-Series-Library](https://github.com/ZhengWr/Time-Series-Library?tab=readme-ov-file)中的数据集，似乎并不能直接运行代码，因为Time-Series-Library将所有的子数据集合成了一个大的数据集。我想问一下您在进行DLinear等模型的实验的过程中是如何解决这个问题的呢？您是将resample后的子数据集合成为一个大的数据集，还是说针对每个子数据集训练不同的模型呢？
另外方便的话可以加个微信交流一下吗？我可以之后将我的微信发到您的邮箱。

**Comment by duanjufang** [comment]
如果要调用Time Series Library中的DLinear，需要对输入输出做相应的改动以适应不同数据格式。
论文中的邮箱由于工作调动已无法使用，可以联系jfdforwork@163.com
